### ISSUE TITLE
Provide options

### ISSUE THREAD

**Issue by KalitaAlexey** [BloodDragon2580/QuickChat#1]
Hi. Personally, I could reduce width and disable actions (pull, leave group and etc), but some people probably wouldn't have an idea how to do it. Let me know if you're still maintaining this project. We could figure out means to implement it (if you didn't think of it). I could even provide a pull request at some point.

**Comment by BloodDragon2580** [comment]
I would be interested in changes maybe you could create an options page in which you can deactivate or activate various things. A pull request would be an advantage.

**Comment by BloodDragon2580** [comment]
I currently have to update many other add-ons so I didn't have time to change anything here.

**Comment by KalitaAlexey** [comment]
Okay. I'll investigate how pages are created.

**Comment by BloodDragon2580** [comment]
I think leave group we can delete but the others like pull, ready and roll we should enabe or disable. The size is a problem for me too it's very width but nothing I try wil work 😒

**Comment by KalitaAlexey** [comment]
Have you tried https://wow.gamepedia.com/API_FontString_GetStringWidth?

**Comment by BloodDragon2580** [comment]
No

**Comment by KalitaAlexey** [comment]
Options page can be implemented via code or xml. What way do you prefer?
https://wowwiki.fandom.com/wiki/Using_the_Interface_Options_Addons_panel

**Comment by BloodDragon2580** [comment]
Since you put so much effort into it, you can decide that. Take what is easier for you.

**Comment by KalitaAlexey** [comment]
I'll choose lua then. XML is more beautiful, but lua gets the job done + it'll be easier to modify.

**Comment by KalitaAlexey** [comment]
What is QC_Settings.bt?

**Comment by BloodDragon2580** [comment]
At the beginning I tried to make a settings page, but then gave up. Must be from back then.

**Comment by KalitaAlexey** [comment]
Is there a reason you believe QC is a safe prefix to use and that it won't overlap?
I'm not very familiar with WoW addons. Do you think QuickChat_Point and QuickChat_Settings is a better alternative?

**Comment by BloodDragon2580** [comment]
We can change this. I have make this becouse it's small. 😁

**Comment by BloodDragon2580** [comment]
I must go to work now. If you want to change or improve something, just do it and make a pull request. I will then look at it and test it. Thank you very much for your effort.

**Comment by KalitaAlexey** [comment]
I'm about to open a pull request. Have a good day.

**Comment by BloodDragon2580** [comment]
Thx bro.
