### ISSUE TITLE
Issue with the addon in 11.0.0.5

### ISSUE THREAD

**Issue by MedianAura** [BloodDragon2580/QuickChat#13]
4 Lua Error on launch 

`1x QuickChat/main.lua:205: attempt to index field 'mainConfigurationFrame' (a nil value)
[string "@QuickChat/main.lua"]:205: in function `?'
[string "@QuickChat/main.lua"]:222: in function <QuickChat/main.lua:222>

Locals:
self = Frame {
}
arg1 = "QuickChat"
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'mainConfigurationFrame' (a nil value)"
QC = <table> {
}`

`1x ...faceQuickChat/Configuration/ButtonsFrame.lua:3: attempt to index field 'mainConfigurationFrame' (a nil value)
[string "@QuickChat/Configuration/ButtonsFrame.lua"]:3: in main chunk

Locals:
frame = QuickChat_BtnCfgFrame {
 name = "Buttons"
}
(*temporary) = nil
(*temporary) = "QuickChat_BtnCfgFrame"
(*temporary) = nil
(*temporary) = "attempt to index field 'mainConfigurationFrame' (a nil value)"
`

`1x ...faceQuickChat/Configuration/GeneralFrame.lua:3: attempt to index field 'mainConfigurationFrame' (a nil value)
[string "@QuickChat/Configuration/GeneralFrame.lua"]:3: in main chunk

Locals:
frame = QuickChat_GenCfgFrame {
 name = "General"
}
(*temporary) = nil
(*temporary) = "QuickChat_GenCfgFrame"
(*temporary) = nil
(*temporary) = "attempt to index field 'mainConfigurationFrame' (a nil value)"
`

`1x QuickChat/Configuration/MainFrame.lua:3: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@QuickChat/Configuration/MainFrame.lua"]:3: in main chunk

Locals:
frame = QuickChat_MainCfgFrame {
 name = "QuickChat"
}
(*temporary) = nil
(*temporary) = QuickChat_MainCfgFrame {
 name = "QuickChat"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"
`

**Comment by BloodDragon2580** [comment]
fixed tomorrow in the next version

**Comment by BloodDragon2580** [comment]
should be fixed
