### ISSUE TITLE
Make buttons take as much space as their text needs

### ISSUE THREAD

**Issue by KalitaAlexey** [BloodDragon2580/QuickChat#3]
Most people probably rely on colors instead of labels. For most people 1-2 characters would be enough to distinguish.
Having this as option will make it easier for people.

The following options are suggested:
* A separate option for each button label
* Min width = 40

I'll start working on it. Just making sure we don't work on the same.

**Comment by BloodDragon2580** [comment]
You are very welcome to work on it. As I already mentioned, I have to update some other addons little by little. Your help is really great. I also had an idea for the settings page. If you have the time, you can open an area for a small text. For example, "please perform a reload after a change." Text for that I would finish the days.

**Comment by KalitaAlexey** [comment]
Yeah. I started working on it and the first thing I faced was labels :) I need to read about them.

**Comment by BloodDragon2580** [comment]
Take your time. I know how it is when you have big plans but you can't get any further. Have a job and a wife and 2 children. I don't have the time I want

**Comment by BloodDragon2580** [comment]
I mean Text like this:

![Screenshot_20201105_215802](https://user-images.githubusercontent.com/1429236/98295544-039a0f80-1fb2-11eb-8990-c17aabcdab0b.jpg)

**Comment by BloodDragon2580** [comment]
local QuickChatSettingsTitle = QuickChatSettings.panel:CreateFontString("QuickChatSettingsTitle", "OVERLAY", "ChatFontNormal")
QuickChatSettingsTitle:SetPoint("TOP", QuickChatSettings.panel, "TOP",0,-10) 
QuickChatSettingsTitle:SetText("|cffe1a500 Quick Chat Settings")

**Comment by BloodDragon2580** [comment]
Text for the Settings Page is finish only must make it Translatable.

**Comment by KalitaAlexey** [comment]
Yea. I'll continue next week hopefully.

**Comment by BloodDragon2580** [comment]
No Problem bro

**Comment by BloodDragon2580** [comment]
The settings page looks a little better now:
![newsettings](https://user-images.githubusercontent.com/1429236/98440001-41a04c00-20f6-11eb-8014-049b51a6b035.jpg)

**Comment by KalitaAlexey** [comment]
I'm trying to make Slider look like in the Blizzard's UI, but I don't understand how they display text above it. Any ideas? :)

**Comment by BloodDragon2580** [comment]
Can you show me an example screenshot. My English is not that good.

**Comment by KalitaAlexey** [comment]
![image](https://user-images.githubusercontent.com/11215191/99182740-e0a4f380-2747-11eb-9272-19c9aa3accda.png)

I have no idea how to do it :)

**Comment by BloodDragon2580** [comment]
We would have to look how it looks with the different languages. Don't know if that's enough.

**Comment by KalitaAlexey** [comment]
I'm talking about Min Width, but all buttons will also have their width set to fit the label.

**Comment by BloodDragon2580** [comment]
ok

**Comment by KalitaAlexey** [comment]
![image](https://user-images.githubusercontent.com/11215191/99183744-26b18580-274f-11eb-90e9-c13200408aa4.png)
That's how it looks like when the button's width depends on the text.

**Comment by BloodDragon2580** [comment]
Ok and when we now look the width depends on the frame.

**Comment by KalitaAlexey** [comment]
Ofc :)

**Comment by KalitaAlexey** [comment]
![image](https://user-images.githubusercontent.com/11215191/99185024-1f42aa00-2758-11eb-90a7-3e87740e0ae0.png)
Should the frame's padding be increased? (The area  to the left and to the right of the buttons. The empty space).

**Comment by BloodDragon2580** [comment]
A little becouse moving.

**Comment by KalitaAlexey** [comment]
Yes, that was my though :)

**Comment by KalitaAlexey** [comment]
![image](https://user-images.githubusercontent.com/11215191/99185105-c45d8280-2758-11eb-8f04-0b1c32bc81b5.png)

**Comment by BloodDragon2580** [comment]
Ok thats it. Looks fine.

**Comment by KalitaAlexey** [comment]
I discussed renaming with my friends and as I thought this feature most likely wouldn't be used.
People rarely want to customize things unless it makes them uneasy.
The reason I'm backing off is that I would have to implement tab or subpages and I don't think it's worth it.
However, they said it would be better if it was just shorter from the beginning.
I could suggest shorter names for buttons in russian or we can keep it as is.
What do you think?

I still think we want to have adaptive buttons though (the behavior on the screenshot above).

**Comment by BloodDragon2580** [comment]
I think it is good on your screenshot.

**Comment by BloodDragon2580** [comment]
can you send me a pull request with this changes from here?

**Comment by KalitaAlexey** [comment]
Sure. I'll do it today.

**Comment by BloodDragon2580** [comment]
thx bro
