### ISSUE TITLE
Bug: Buttons are created each time you move your character

### ISSUE THREAD

**Issue by KalitaAlexey** [BloodDragon2580/QuickChat#4]
I added print to the function that adds a button and started moving.
At that moment I saw my chat overwhelmed with log message.
It could greatly impact users' experience.

**Comment by BloodDragon2580** [comment]
I can't test it at the Moment. I have no play time. Can you send me a screen?

**Comment by KalitaAlexey** [comment]
![image](https://user-images.githubusercontent.com/11215191/99185414-ce808080-275a-11eb-9061-af9d2c27f8b2.png)

I made 2 steps :)

**Comment by BloodDragon2580** [comment]
I dont understand why.

**Comment by KalitaAlexey** [comment]
```
function frame:PLAYER_STOPPED_MOVING(arg1)
	if type(QC_Point)=="table" and QC.F~=nil then update_frame_btn(); end
end
function frame:PLAYER_STARTED_MOVING(arg1)
	if type(QC_Point)=="table" and QC.F~=nil then update_frame_btn(); end
end
```
Dunno :)

**Comment by BloodDragon2580** [comment]
Ahhh lol dont have See this. Fuck.

**Comment by BloodDragon2580** [comment]
Remove this liens should fix this. Must test it when I have play time end this month.

**Comment by BloodDragon2580** [comment]
```
function frame:PLAYER_STOPPED_MOVING(arg1)
	if type(QC_Point)=="table" and QC.F~=nil then update_frame_btn(); end
end
function frame:PLAYER_STARTED_MOVING(arg1)
	if type(QC_Point)=="table" and QC.F~=nil then update_frame_btn(); end
end

frame:RegisterEvent("PLAYER_STOPPED_MOVING");
frame:RegisterEvent("PLAYER_STARTED_MOVING");
```

Must delete.

**Comment by KalitaAlexey** [comment]
What is CRITERIA_UPDATE for?

**Comment by BloodDragon2580** [comment]
Must test it when I have play time it's long time ago I have Do this.

**Comment by KalitaAlexey** [comment]
I see that CRITERIA_UPDATE also happens when I just run.
